version: "3.8"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET:-production-pseudo}
    volumes:
      - .:/local/symfony-5.2.4

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
      target: ${TARGET:-production-pseudo}
    volumes:
      - .:/local/symfony-5.2.4

  node:
    build:
      context: .
      dockerfile: node.dockerfile
      target: ${TARGET:-production-pseudo}
    volumes:
      - .:/local/symfony-5.2.4

  mysql:
    image: mysql:8.0.23
    volumes:
      - .:/local/symfony-5.2.4
      - mysql_data:/var/lib/myswl
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  mysql_data:
  node_modules:
